include:
  - project: affinidi/foundational/genesis/projen/genesis-pipeline
    ref: main
    file:
      - /stack/rust-lib.yml

# enable once the libs are published to crates
# as for now they are referenced via '../'
# which breaks the jobs.

clippy:processor:
  extends: .common
  before_script:
    - pwd
    - cd atn-atm-processor/
  script:
    - cargo clippy --color always --no-deps

clippy:mediator:
  extends: .common
  before_script:
    - pwd
    - cd atn-atm-mediator/
  script:
    - cargo clippy --color always --no-deps

clippy:didcomm:
  extends: .common
  before_script:
    - pwd
    - cd atn-atm-didcomm/
  script:
    - cargo clippy --color always --no-deps

build:
  rules:
    - when: never

clippy:
  rules:
    - when: never

fmt:
  rules:
    - when: never

license:
  rules:
    - when: never
