[workspace]
members = [
    "affinidi-messaging-didcomm",
    "affinidi-messaging-sdk",
    "affinidi-messaging-mediator",
    "affinidi-messaging-processor",
]
resolver = "2"

[workspace.package]
version = '0.7.1'
edition = "2021"
authors = ["Glenn Gore <glenn@affinidi.com>"]
description = "Affinidi Trusted Messaging"
readme = "README.md"
homepage = "https://affinidi.com/"
keywords = ["did", "ssi", "ATM", "affinidi"]
publish = true
license = "Apache-2.0"

[workspace.dependencies]
# change "0" to "0.x" once the new version is published as 0.1.3 is not compatible with 0.7.1
affinidi-messaging-sdk = { version = "0", path = "./affinidi-messaging-sdk" }
affinidi-messaging-didcomm = { version = "0", path = "./affinidi-messaging-didcomm" }
affinidi-did-resolver-cache-sdk = { version = "0.1.7" }
did-peer = { version = "0.1.7" }
clap = { version = "4.5", features = ["derive"] }
