[workspace]
members = [
    "affinidi-messaging-didcomm",
    "affinidi-messaging-sdk",
    "affinidi-messaging-mediator",
    "affinidi-messaging-processor",
]
resolver = "2"

[workspace.package]
version = '0.8.0'
edition = "2021"
authors = ["Glenn Gore <glenn@affinidi.com>"]
description = "Affinidi Messaging"
readme = "README.md"
homepage = "https://affinidi.com/"
keywords = ["did", "ssi", "ATM", "affinidi"]
publish = true
license = "Apache-2.0"

[workspace.dependencies]
# change "0" to "0.x" once the new version is published as 0.1.3 is not compatible with 0.7.1
affinidi-messaging-sdk = { version = "0.8", path = "./affinidi-messaging-sdk" }
affinidi-messaging-didcomm = { version = "0.8", path = "./affinidi-messaging-didcomm" }
affinidi-did-resolver-cache-sdk = { version = "0.1.11", path = "../affinidi-did-resolver/affinidi-did-resolver-cache-sdk" }
deadpool-redis = { version = "0.18", features = ["rt_tokio_1"] }
did-peer = { version = "0.1" }
clap = { version = "4.5", features = ["derive"] }
rcgen = { version = "0.13", default-features = false, features = [
    "aws_lc_rs",
    "pem",
] }
redis = { version = "0.27", features = [
    "tokio-rustls-comp",
    "tls-rustls-insecure",
] }
reqwest = { version = "0.12", features = ["rustls-tls-manual-roots", "json"] }
ssi = "0.9"
time = "0.3"
tokio = { version = "1.40", features = ["full"] }
tokio-stream = "0.1"
toml = "0.8"
tower-http = { version = "0.6", features = ["cors", "trace", "limit"] }
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_info",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.10", features = ["v4", "fast-rng"] }
