[workspace]
members = [
    "affinidi-messaging-didcomm",
    "affinidi-messaging-sdk",
    "affinidi-messaging-mediator",
    "affinidi-messaging-processor",
]
resolver = "2"

[workspace.package]
version = '0.7.0'
edition = "2021"
authors = ["Glenn Gore <glenn@affinidi.com>"]
description = "Affinidi Trusted Messaging"
readme = "README.md"
homepage = "https://affinidi.com/"
keywords = ["did", "ssi", "ATM", "affinidi"]
publish = true
license = "Apache-2.0"

[workspace.dependencies]
affinidi-did-resolver-cache-sdk = { version = "0.1.6" }
did-peer = { version = "0.1.6" }
clap = { version = "4.5", features = ["derive"] }
