version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: atn_atm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  redis-data:
  redis-config:
