### log_level: trace debug info warn error
### default: info
log_level = "info"

### listen_address: <ip_address>:<tcp_port> that this service will listen on.
### Default: 0.0.0.0:7037
listen_address = "${LISTEN_ADDRESS:0.0.0.0:7037}"

### database_file: Where to store local data
### Default: ./mediator_db.redb
database_file = "${DATABASE_FILE:./mediator_db.redb}"

### database_max_size_mb: Maximum size of the database in Megabytes
### Default: 100
database_max_size_mb = "${database_max_size_mb:100}"

### mediator_did: DID of the mediator
### REQUIRED!
mediator_did = "${MEDIATOR_DID:did:peer:2.Vz6Mkp9f4p6rSJkgbxTpPXL861PSN6EB996fQv5vCq5Q9C5Me.EzQ3shpFNDUgbePPhbLmwNcTiNSAhcb511urztSmT7aavVamJ3.SeyJ0IjoiRElEQ29tbU1lc3NhZ2luZyIsInMiOnsidXJpIjoiaHR0cHM6Ly8xMjcuMC4wLjE6NzAzNyIsImEiOlsiZGlkY29tbS92MiJdLCJyIjpbXX19}"

### mediator_secrets: Secrets of the mediator
### REQUIRED: Location of secrets (supports file:// only)
### Example file:[{"id": "#key-1", "crv": "secp256k1", "kty": "EC", "d": "...", "x": "...", "y": "..."}, {}]
### NOTE: The key identifiers (id) must match the key identifiers in the mediator_did
mediator_secrets = "${MEDIATOR_SECRETS:file://./conf/secrets.json}"

### mediator_allowed_dids: DID's that are allowed to send messages through this mediator
### Default: Filename of a file containing a list of allowed DIDs
mediator_allowed_dids = "${MEDIATOR_ALLOWED_DIDS:./conf/mediator_allowed_dids.txt}"

### mediator_denied_dids: DID's that are denied to send messages through this mediator
### Default: Filename of a file containing a list of denied DIDs
mediator_denied_dids = "${MEDIATOR_DENIED_DIDS:./conf/mediator_denied_dids.txt}"
