name: checks

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  push:
    branches:
      - FTL-17136_integration_test
jobs:
  rust-pipeline:
    uses: affinidi/pipeline-rust/.github/workflows/checks.yaml@b60c4f85ab0de4f803e1093978bfd2f3765516f5
    secrets: inherit
    with:
      auditIgnore: 'RUSTSEC-2022-0040,RUSTSEC-2023-0071,RUSTSEC-2024-0373'
      coverage: 10
