name: Licenses
on: [push, pull_request]
jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check bans licenses sources
